<?php

$labels['imap_labels'] = 'Schlagwörter';
$labels['labeladd'] = 'Schlagwort hinzufügen';
$labels['labelform'] = "Schlagwort bearbeiten";
$labels['imap_label'] = 'Schlagwort';
$labels['imap_name'] = 'Name';
$labels['imap_color'] = 'Farbe';
$labels['arialabel-labelform'] = "Schlagwort bearbeiten";

$labels['dberror'] = 'Die Daten konnten nicht geladen werden.';
$labels['label_notempty'] = 'Das Schlagwort kann nicht leer sein';
$labels['name_notempty'] = 'Der Name kann nicht leer sein';
$labels['saved'] = 'Das Schlagwort wurde erfolgreich gespeichert';

?>