<?php

$labels['imap_labels'] = 'Tags';
$labels['labeladd'] = 'Add Tag';
$labels['labelform'] = "Edit Tag";
$labels['imap_label'] = 'Tag';
$labels['imap_name'] = 'Name';
$labels['imap_color'] = 'Color';
$labels['arialabel-labelform'] = "Edit Tag";

$labels['dberror'] = 'An error occurred while fetching data from database';
$labels['label_notempty'] = 'The label cannot be empty';
$labels['name_notempty'] = 'The name cannot be empty';
$labels['saved'] = 'The label has been successfully saved';

?>